version: '3.8'

services:
  quick-fshare-all-in-one:
    image: zj591227045/quick-fshare:0.1.3
    container_name: quick-fshare-single
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}
      - DB_PATH=/app/database/fshare.db
      - UPLOAD_PATH=/app/uploads
      - THUMBNAIL_PATH=/app/thumbnails
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-104857600}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
    volumes:
      - app_database:/app/database
      - app_uploads:/app/uploads
      - app_thumbnails:/app/thumbnails
      - app_logs:/app/logs
      - app_data:/app/data
      - ${SHARED_VOLUMES:-./data}:/app/shared:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_database:
    driver: local
  app_uploads:
    driver: local
  app_thumbnails:
    driver: local
  app_logs:
    driver: local
  app_data:
    driver: local 